apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 7
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec: 
      containers:
        - name: nodeapp
          image: emanzaki/k8s-web-server
          ports:
            - containerPort: 80
